apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflare
spec:
  controller: cloudflare.unmango.dev/ingress-controller
