name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          install-mode: none

  dist-clean:
    name: Verify Worktree Clean
    runs-on: ubuntu-latest
    env:
      IMG: ghcr.io/unmango/cloudflare-operator:v0.0.1
    strategy:
      matrix:
        target:
          - helm
          - build-installer
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: make ${{ matrix.target }}
      - run: git diff --exit-code
