name: Release

on:
  push:
    branches: [main]
    tags: [v*.*.*]

jobs:
  chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: dist
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
