name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Install kind
        run: go install sigs.k8s.io/kind

      - name: Verify kind installation
        run: kind version

      - name: Build and load Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          cache-from: type=gha
          tags: ghcr.io/${{ github.repository }}

      - name: Running Test e2e
        run: make test-e2e
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
